# Importing DataSet

In [2]:
import pandas as pd
import numpy as np

np.random.seed(37)
df = pd.read_csv("common-dataset.csv")
df.head()

user_id  touch_type  touch  finger   palm   fist   1  2   3   4  ...  3191  \
0        0           0  False   False  False  False   4  0  12 -16  ...   -51   
1        0           0  False   False  False  False -52 -2  17   1  ...   -36   
2        0           0  False   False  False  False   2  7  14  -5  ...     1   
3        0           0  False   False  False  False   0  6  10   8  ...     1   
4        0           0  False   False  False  False   2  5   3   0  ...   -25   

   3192  3193  3194  3195  3196  3197  3198  3199  3200  
0     4     1     3   -42     2     3    61     2    -1  
1    -1    49     6   -58     8    49    63    47     6  
2    55    54   -51   -26    55    56     9    55    52  
3     2    28     2     1     9    55    53    -7    51  
4    51    -6   -45    -4    61    48    60    46     5  

[5 rows x 3206 columns]

In [3]:
data=df.values

# Splitting DataSet

In [4]:
y_user_id = data[:,0]
y_touch_type = data[:,1]
# y_touch_ver = data[:,2:6]
y_user_id=y_user_id.astype('int64')
y_touch_type=y_touch_type.astype('int64')
# y_touch_ver=y_touch_ver.astype('bool')
y_user_id
# y_touch_ver

y_touch_type

array([0, 0, 0, ..., 9, 9, 0], dtype=int64)

In [5]:
x=data[:,6:]
x=x.astype('int64')
x

array([[  4,   0,  12, ...,  61,   2,  -1],
       [-52,  -2,  17, ...,  63,  47,   6],
       [  2,   7,  14, ...,   9,  55,  52],
       ...,
       [  8,  -9, -12, ...,  20,  64,  68],
       [ 56,   0,   0, ...,   6,  -6,  51],
       [ 11,  -1, -12, ...,   9,  52,  52]], dtype=int64)

# Setting Train and Test Data

In [6]:
from sklearn.model_selection import train_test_split
x_train_user_id, x_test_user_id, y_train_user_id, y_test_user_id = train_test_split(x, y_user_id, test_size = 0.25, random_state = 37)
y_train_user_id

array([ 7,  1,  8, ..., 11,  5, 28], dtype=int64)

# Fitting Train Data to Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train_user_id,y_train_user_id)

LinearRegression()

In [8]:
print(LR.coef_)

[ 1.11139947e-03  4.39782538e-05 -1.28160200e-03 ... -4.94133125e-04
 -1.78551432e-03  2.75066127e-03]


In [9]:
print(LR.intercept_)

13.745291651888634


In [10]:
y_prediction =  LR.predict(x_test_user_id)

In [11]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
score=r2_score(y_test_user_id,y_prediction)
print('r2 score is ',score)
print('mean_sqrd_error is==',mean_squared_error(y_test_user_id,y_prediction))
print('root_mean_squared error of is==',np.sqrt(mean_squared_error(y_test_user_id,y_prediction)))

r2 score is  0.9699621264807289
mean_sqrd_error is== 2.413714180653816
root_mean_squared error of is== 1.553613266116705


# Pre-Processing with Standart Scaler
Standart scaler standardize features by removing the mean and scaling to unit variance.

In [12]:
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
x_train_touch_type, x_test_touch_type, y_train_touch_type, y_test_touch_type = train_test_split(x, y_touch_type, test_size = 0.25, random_state = 37)
from sklearn import preprocessing


sc_x = preprocessing.StandardScaler() #0.20
sc_y = preprocessing.StandardScaler()
x_train_touch_type = sc_x.fit_transform(x_train_touch_type)
x_test_touch_type = sc_x.fit_transform(x_test_touch_type)


# Using Linear Regression on Touch Type

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

LR = LinearRegression()
LR.fit(x_train_touch_type,y_train_touch_type)
y_prediction =  LR.predict(x_test_touch_type)
score=r2_score(y_test_touch_type,y_prediction)
print('r2 score is ',score)
print('mean_sqrd_error is==',mean_squared_error(y_test_touch_type,y_prediction))
print('root_mean_squared error of is==',np.sqrt(mean_squared_error(y_test_touch_type,y_prediction)))

r2 score is  0.1806099704415246
mean_sqrd_error is== 7.301911582428097
root_mean_squared error of is== 2.7022049482650456


We have a bad result on linear regression so we choose to go with Lasso.

In [14]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(x_train_touch_type, y_train_touch_type)
y_prediction =  clf.predict(x_test_touch_type)
score=r2_score(y_test_touch_type,y_prediction)
print('r2 score is ',score)
print('mean_sqrd_error is==',mean_squared_error(y_test_touch_type,y_prediction))
print('root_mean_squared error of is==',np.sqrt(mean_squared_error(y_test_touch_type,y_prediction)))

r2 score is  0.5607561959780787
mean_sqrd_error is== 3.9142768454550207
root_mean_squared error of is== 1.9784531446195588
